###############################################################################
# Copyright 2019 Intel Corporation
# All Rights Reserved.
#
# If this  software was obtained  under the  Intel Simplified  Software License,
# the following terms apply:
#
# The source code,  information  and material  ("Material") contained  herein is
# owned by Intel Corporation or its  suppliers or licensors,  and  title to such
# Material remains with Intel  Corporation or its  suppliers or  licensors.  The
# Material  contains  proprietary  information  of  Intel or  its suppliers  and
# licensors.  The Material is protected by  worldwide copyright  laws and treaty
# provisions.  No part  of  the  Material   may  be  used,  copied,  reproduced,
# modified, published,  uploaded, posted, transmitted,  distributed or disclosed
# in any way without Intel's prior express written permission.  No license under
# any patent,  copyright or other  intellectual property rights  in the Material
# is granted to  or  conferred  upon  you,  either   expressly,  by implication,
# inducement,  estoppel  or  otherwise.  Any  license   under such  intellectual
# property rights must be express and approved by Intel in writing.
#
# Unless otherwise agreed by Intel in writing,  you may not remove or alter this
# notice or  any  other  notice   embedded  in  Materials  by  Intel  or Intel's
# suppliers or licensors in any way.
#
#
# If this  software  was obtained  under the  Apache License,  Version  2.0 (the
# "License"), the following terms apply:
#
# You may  not use this  file except  in compliance  with  the License.  You may
# obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
#
# Unless  required  by   applicable  law  or  agreed  to  in  writing,  software
# distributed under the License  is distributed  on an  "AS IS"  BASIS,  WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the   License  for the   specific  language   governing   permissions  and
# limitations under the License.
###############################################################################

 
.text
.p2align 4, 0x90
 
pByteSwp:
.byte  3,2,1,0, 7,6,5,4, 11,10,9,8, 15,14,13,12 
.p2align 4, 0x90
 
.globl _UpdateSHA256

 
_UpdateSHA256:
 
    push         %rbx
 
    push         %rbp
 
    push         %r12
 
    push         %r13
 
    push         %r14
 
    push         %r15
 
    sub          $(40), %rsp
 
    movslq       %edx, %rdx
    movq         %rdx, (16)(%rsp)
.Lsha256_block_loopgas_1: 
    movdqu       (%rsi), %xmm0
    movdqu       (16)(%rsi), %xmm1
    movdqu       (32)(%rsi), %xmm2
    movdqu       (48)(%rsi), %xmm3
    movl         (%rdi), %eax
    movl         (4)(%rdi), %ebx
    movl         (8)(%rdi), %edx
    movl         (12)(%rdi), %r8d
    movl         (16)(%rdi), %r9d
    movl         (20)(%rdi), %r10d
    movl         (24)(%rdi), %r11d
    movl         (28)(%rdi), %r12d
    movdqa       pByteSwp(%rip), %xmm6
    pshufb       %xmm6, %xmm0
    movdqa       %xmm0, %xmm7
    paddd        (%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r12d
    mov          %r9d, %r13d
    ror          $(6), %r13d
    mov          %r9d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r11d, %r14d
    and          %r9d, %r14d
    xor          %r11d, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    add          %r12d, %r8d
    mov          %eax, %r13d
    ror          $(2), %r13d
    mov          %eax, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %edx, %r14d
    xor          %ebx, %edx
    and          %edx, %r14d
    xor          %ebx, %edx
    xor          %edx, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    addl         (4)(%rsp), %r11d
    mov          %r8d, %r13d
    ror          $(6), %r13d
    mov          %r8d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r10d, %r14d
    and          %r8d, %r14d
    xor          %r10d, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    add          %r11d, %edx
    mov          %r12d, %r13d
    ror          $(2), %r13d
    mov          %r12d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %ebx, %r14d
    xor          %eax, %ebx
    and          %ebx, %r14d
    xor          %eax, %ebx
    xor          %ebx, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    addl         (8)(%rsp), %r10d
    mov          %edx, %r13d
    ror          $(6), %r13d
    mov          %edx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r9d, %r14d
    and          %edx, %r14d
    xor          %r9d, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    add          %r10d, %ebx
    mov          %r11d, %r13d
    ror          $(2), %r13d
    mov          %r11d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %eax, %r14d
    xor          %r12d, %eax
    and          %eax, %r14d
    xor          %r12d, %eax
    xor          %eax, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    addl         (12)(%rsp), %r9d
    mov          %ebx, %r13d
    ror          $(6), %r13d
    mov          %ebx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r8d, %r14d
    and          %ebx, %r14d
    xor          %r8d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    add          %r9d, %eax
    mov          %r10d, %r13d
    ror          $(2), %r13d
    mov          %r10d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r12d, %r14d
    xor          %r11d, %r12d
    and          %r12d, %r14d
    xor          %r11d, %r12d
    xor          %r12d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    pshufb       %xmm6, %xmm1
    movdqa       %xmm1, %xmm7
    paddd        (16)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r8d
    mov          %eax, %r13d
    ror          $(6), %r13d
    mov          %eax, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %edx, %r14d
    and          %eax, %r14d
    xor          %edx, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    add          %r8d, %r12d
    mov          %r9d, %r13d
    ror          $(2), %r13d
    mov          %r9d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r11d, %r14d
    xor          %r10d, %r11d
    and          %r11d, %r14d
    xor          %r10d, %r11d
    xor          %r11d, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    addl         (4)(%rsp), %edx
    mov          %r12d, %r13d
    ror          $(6), %r13d
    mov          %r12d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %ebx, %r14d
    and          %r12d, %r14d
    xor          %ebx, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    add          %edx, %r11d
    mov          %r8d, %r13d
    ror          $(2), %r13d
    mov          %r8d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r10d, %r14d
    xor          %r9d, %r10d
    and          %r10d, %r14d
    xor          %r9d, %r10d
    xor          %r10d, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    addl         (8)(%rsp), %ebx
    mov          %r11d, %r13d
    ror          $(6), %r13d
    mov          %r11d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %eax, %r14d
    and          %r11d, %r14d
    xor          %eax, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    add          %ebx, %r10d
    mov          %edx, %r13d
    ror          $(2), %r13d
    mov          %edx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r9d, %r14d
    xor          %r8d, %r9d
    and          %r9d, %r14d
    xor          %r8d, %r9d
    xor          %r9d, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    addl         (12)(%rsp), %eax
    mov          %r10d, %r13d
    ror          $(6), %r13d
    mov          %r10d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %r12d, %r14d
    and          %r10d, %r14d
    xor          %r12d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    add          %eax, %r9d
    mov          %ebx, %r13d
    ror          $(2), %r13d
    mov          %ebx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %r8d, %r14d
    xor          %edx, %r8d
    and          %r8d, %r14d
    xor          %edx, %r8d
    xor          %r8d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    pshufb       %xmm6, %xmm2
    movdqa       %xmm2, %xmm7
    paddd        (32)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r12d
    mov          %r9d, %r13d
    ror          $(6), %r13d
    mov          %r9d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r11d, %r14d
    and          %r9d, %r14d
    xor          %r11d, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    add          %r12d, %r8d
    mov          %eax, %r13d
    ror          $(2), %r13d
    mov          %eax, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %edx, %r14d
    xor          %ebx, %edx
    and          %edx, %r14d
    xor          %ebx, %edx
    xor          %edx, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    addl         (4)(%rsp), %r11d
    mov          %r8d, %r13d
    ror          $(6), %r13d
    mov          %r8d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r10d, %r14d
    and          %r8d, %r14d
    xor          %r10d, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    add          %r11d, %edx
    mov          %r12d, %r13d
    ror          $(2), %r13d
    mov          %r12d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %ebx, %r14d
    xor          %eax, %ebx
    and          %ebx, %r14d
    xor          %eax, %ebx
    xor          %ebx, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    addl         (8)(%rsp), %r10d
    mov          %edx, %r13d
    ror          $(6), %r13d
    mov          %edx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r9d, %r14d
    and          %edx, %r14d
    xor          %r9d, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    add          %r10d, %ebx
    mov          %r11d, %r13d
    ror          $(2), %r13d
    mov          %r11d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %eax, %r14d
    xor          %r12d, %eax
    and          %eax, %r14d
    xor          %r12d, %eax
    xor          %eax, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    addl         (12)(%rsp), %r9d
    mov          %ebx, %r13d
    ror          $(6), %r13d
    mov          %ebx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r8d, %r14d
    and          %ebx, %r14d
    xor          %r8d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    add          %r9d, %eax
    mov          %r10d, %r13d
    ror          $(2), %r13d
    mov          %r10d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r12d, %r14d
    xor          %r11d, %r12d
    and          %r12d, %r14d
    xor          %r11d, %r12d
    xor          %r12d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    pshufb       %xmm6, %xmm3
    movdqa       %xmm3, %xmm7
    paddd        (48)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r8d
    mov          %eax, %r13d
    ror          $(6), %r13d
    mov          %eax, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %edx, %r14d
    and          %eax, %r14d
    xor          %edx, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    add          %r8d, %r12d
    mov          %r9d, %r13d
    ror          $(2), %r13d
    mov          %r9d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r11d, %r14d
    xor          %r10d, %r11d
    and          %r11d, %r14d
    xor          %r10d, %r11d
    xor          %r11d, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    addl         (4)(%rsp), %edx
    mov          %r12d, %r13d
    ror          $(6), %r13d
    mov          %r12d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %ebx, %r14d
    and          %r12d, %r14d
    xor          %ebx, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    add          %edx, %r11d
    mov          %r8d, %r13d
    ror          $(2), %r13d
    mov          %r8d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r10d, %r14d
    xor          %r9d, %r10d
    and          %r10d, %r14d
    xor          %r9d, %r10d
    xor          %r10d, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    addl         (8)(%rsp), %ebx
    mov          %r11d, %r13d
    ror          $(6), %r13d
    mov          %r11d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %eax, %r14d
    and          %r11d, %r14d
    xor          %eax, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    add          %ebx, %r10d
    mov          %edx, %r13d
    ror          $(2), %r13d
    mov          %edx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r9d, %r14d
    xor          %r8d, %r9d
    and          %r9d, %r14d
    xor          %r8d, %r9d
    xor          %r9d, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    addl         (12)(%rsp), %eax
    mov          %r10d, %r13d
    ror          $(6), %r13d
    mov          %r10d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %r12d, %r14d
    and          %r10d, %r14d
    xor          %r12d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    add          %eax, %r9d
    mov          %ebx, %r13d
    ror          $(2), %r13d
    mov          %ebx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %r8d, %r14d
    xor          %edx, %r8d
    and          %r8d, %r14d
    xor          %edx, %r8d
    xor          %r8d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    pshufd       $(250), %xmm3, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm0, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm0, %xmm7
    pshufd       $(165), %xmm2, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm1, %xmm5
    palignr      $(12), %xmm0, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm3, %xmm6
    palignr      $(12), %xmm2, %xmm6
    pshufd       $(250), %xmm0, %xmm0
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm0
    paddd        %xmm5, %xmm0
    paddd        %xmm6, %xmm0
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm0, %xmm0
    palignr      $(8), %xmm7, %xmm0
    movdqa       %xmm0, %xmm7
    paddd        (64)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r12d
    mov          %r9d, %r13d
    ror          $(6), %r13d
    mov          %r9d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r11d, %r14d
    and          %r9d, %r14d
    xor          %r11d, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    add          %r12d, %r8d
    mov          %eax, %r13d
    ror          $(2), %r13d
    mov          %eax, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %edx, %r14d
    xor          %ebx, %edx
    and          %edx, %r14d
    xor          %ebx, %edx
    xor          %edx, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    addl         (4)(%rsp), %r11d
    mov          %r8d, %r13d
    ror          $(6), %r13d
    mov          %r8d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r10d, %r14d
    and          %r8d, %r14d
    xor          %r10d, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    add          %r11d, %edx
    mov          %r12d, %r13d
    ror          $(2), %r13d
    mov          %r12d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %ebx, %r14d
    xor          %eax, %ebx
    and          %ebx, %r14d
    xor          %eax, %ebx
    xor          %ebx, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    addl         (8)(%rsp), %r10d
    mov          %edx, %r13d
    ror          $(6), %r13d
    mov          %edx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r9d, %r14d
    and          %edx, %r14d
    xor          %r9d, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    add          %r10d, %ebx
    mov          %r11d, %r13d
    ror          $(2), %r13d
    mov          %r11d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %eax, %r14d
    xor          %r12d, %eax
    and          %eax, %r14d
    xor          %r12d, %eax
    xor          %eax, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    addl         (12)(%rsp), %r9d
    mov          %ebx, %r13d
    ror          $(6), %r13d
    mov          %ebx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r8d, %r14d
    and          %ebx, %r14d
    xor          %r8d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    add          %r9d, %eax
    mov          %r10d, %r13d
    ror          $(2), %r13d
    mov          %r10d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r12d, %r14d
    xor          %r11d, %r12d
    and          %r12d, %r14d
    xor          %r11d, %r12d
    xor          %r12d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    pshufd       $(250), %xmm0, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm1, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm1, %xmm7
    pshufd       $(165), %xmm3, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm2, %xmm5
    palignr      $(12), %xmm1, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm0, %xmm6
    palignr      $(12), %xmm3, %xmm6
    pshufd       $(250), %xmm1, %xmm1
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm1
    paddd        %xmm5, %xmm1
    paddd        %xmm6, %xmm1
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm1, %xmm1
    palignr      $(8), %xmm7, %xmm1
    movdqa       %xmm1, %xmm7
    paddd        (80)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r8d
    mov          %eax, %r13d
    ror          $(6), %r13d
    mov          %eax, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %edx, %r14d
    and          %eax, %r14d
    xor          %edx, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    add          %r8d, %r12d
    mov          %r9d, %r13d
    ror          $(2), %r13d
    mov          %r9d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r11d, %r14d
    xor          %r10d, %r11d
    and          %r11d, %r14d
    xor          %r10d, %r11d
    xor          %r11d, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    addl         (4)(%rsp), %edx
    mov          %r12d, %r13d
    ror          $(6), %r13d
    mov          %r12d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %ebx, %r14d
    and          %r12d, %r14d
    xor          %ebx, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    add          %edx, %r11d
    mov          %r8d, %r13d
    ror          $(2), %r13d
    mov          %r8d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r10d, %r14d
    xor          %r9d, %r10d
    and          %r10d, %r14d
    xor          %r9d, %r10d
    xor          %r10d, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    addl         (8)(%rsp), %ebx
    mov          %r11d, %r13d
    ror          $(6), %r13d
    mov          %r11d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %eax, %r14d
    and          %r11d, %r14d
    xor          %eax, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    add          %ebx, %r10d
    mov          %edx, %r13d
    ror          $(2), %r13d
    mov          %edx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r9d, %r14d
    xor          %r8d, %r9d
    and          %r9d, %r14d
    xor          %r8d, %r9d
    xor          %r9d, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    addl         (12)(%rsp), %eax
    mov          %r10d, %r13d
    ror          $(6), %r13d
    mov          %r10d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %r12d, %r14d
    and          %r10d, %r14d
    xor          %r12d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    add          %eax, %r9d
    mov          %ebx, %r13d
    ror          $(2), %r13d
    mov          %ebx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %r8d, %r14d
    xor          %edx, %r8d
    and          %r8d, %r14d
    xor          %edx, %r8d
    xor          %r8d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    pshufd       $(250), %xmm1, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm2, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm2, %xmm7
    pshufd       $(165), %xmm0, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm3, %xmm5
    palignr      $(12), %xmm2, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm1, %xmm6
    palignr      $(12), %xmm0, %xmm6
    pshufd       $(250), %xmm2, %xmm2
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm2
    paddd        %xmm5, %xmm2
    paddd        %xmm6, %xmm2
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm2, %xmm2
    palignr      $(8), %xmm7, %xmm2
    movdqa       %xmm2, %xmm7
    paddd        (96)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r12d
    mov          %r9d, %r13d
    ror          $(6), %r13d
    mov          %r9d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r11d, %r14d
    and          %r9d, %r14d
    xor          %r11d, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    add          %r12d, %r8d
    mov          %eax, %r13d
    ror          $(2), %r13d
    mov          %eax, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %edx, %r14d
    xor          %ebx, %edx
    and          %edx, %r14d
    xor          %ebx, %edx
    xor          %edx, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    addl         (4)(%rsp), %r11d
    mov          %r8d, %r13d
    ror          $(6), %r13d
    mov          %r8d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r10d, %r14d
    and          %r8d, %r14d
    xor          %r10d, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    add          %r11d, %edx
    mov          %r12d, %r13d
    ror          $(2), %r13d
    mov          %r12d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %ebx, %r14d
    xor          %eax, %ebx
    and          %ebx, %r14d
    xor          %eax, %ebx
    xor          %ebx, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    addl         (8)(%rsp), %r10d
    mov          %edx, %r13d
    ror          $(6), %r13d
    mov          %edx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r9d, %r14d
    and          %edx, %r14d
    xor          %r9d, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    add          %r10d, %ebx
    mov          %r11d, %r13d
    ror          $(2), %r13d
    mov          %r11d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %eax, %r14d
    xor          %r12d, %eax
    and          %eax, %r14d
    xor          %r12d, %eax
    xor          %eax, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    addl         (12)(%rsp), %r9d
    mov          %ebx, %r13d
    ror          $(6), %r13d
    mov          %ebx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r8d, %r14d
    and          %ebx, %r14d
    xor          %r8d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    add          %r9d, %eax
    mov          %r10d, %r13d
    ror          $(2), %r13d
    mov          %r10d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r12d, %r14d
    xor          %r11d, %r12d
    and          %r12d, %r14d
    xor          %r11d, %r12d
    xor          %r12d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    pshufd       $(250), %xmm2, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm3, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm3, %xmm7
    pshufd       $(165), %xmm1, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm0, %xmm5
    palignr      $(12), %xmm3, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm2, %xmm6
    palignr      $(12), %xmm1, %xmm6
    pshufd       $(250), %xmm3, %xmm3
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm3
    paddd        %xmm5, %xmm3
    paddd        %xmm6, %xmm3
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm3, %xmm3
    palignr      $(8), %xmm7, %xmm3
    movdqa       %xmm3, %xmm7
    paddd        (112)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r8d
    mov          %eax, %r13d
    ror          $(6), %r13d
    mov          %eax, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %edx, %r14d
    and          %eax, %r14d
    xor          %edx, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    add          %r8d, %r12d
    mov          %r9d, %r13d
    ror          $(2), %r13d
    mov          %r9d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r11d, %r14d
    xor          %r10d, %r11d
    and          %r11d, %r14d
    xor          %r10d, %r11d
    xor          %r11d, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    addl         (4)(%rsp), %edx
    mov          %r12d, %r13d
    ror          $(6), %r13d
    mov          %r12d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %ebx, %r14d
    and          %r12d, %r14d
    xor          %ebx, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    add          %edx, %r11d
    mov          %r8d, %r13d
    ror          $(2), %r13d
    mov          %r8d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r10d, %r14d
    xor          %r9d, %r10d
    and          %r10d, %r14d
    xor          %r9d, %r10d
    xor          %r10d, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    addl         (8)(%rsp), %ebx
    mov          %r11d, %r13d
    ror          $(6), %r13d
    mov          %r11d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %eax, %r14d
    and          %r11d, %r14d
    xor          %eax, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    add          %ebx, %r10d
    mov          %edx, %r13d
    ror          $(2), %r13d
    mov          %edx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r9d, %r14d
    xor          %r8d, %r9d
    and          %r9d, %r14d
    xor          %r8d, %r9d
    xor          %r9d, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    addl         (12)(%rsp), %eax
    mov          %r10d, %r13d
    ror          $(6), %r13d
    mov          %r10d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %r12d, %r14d
    and          %r10d, %r14d
    xor          %r12d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    add          %eax, %r9d
    mov          %ebx, %r13d
    ror          $(2), %r13d
    mov          %ebx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %r8d, %r14d
    xor          %edx, %r8d
    and          %r8d, %r14d
    xor          %edx, %r8d
    xor          %r8d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    pshufd       $(250), %xmm3, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm0, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm0, %xmm7
    pshufd       $(165), %xmm2, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm1, %xmm5
    palignr      $(12), %xmm0, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm3, %xmm6
    palignr      $(12), %xmm2, %xmm6
    pshufd       $(250), %xmm0, %xmm0
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm0
    paddd        %xmm5, %xmm0
    paddd        %xmm6, %xmm0
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm0, %xmm0
    palignr      $(8), %xmm7, %xmm0
    movdqa       %xmm0, %xmm7
    paddd        (128)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r12d
    mov          %r9d, %r13d
    ror          $(6), %r13d
    mov          %r9d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r11d, %r14d
    and          %r9d, %r14d
    xor          %r11d, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    add          %r12d, %r8d
    mov          %eax, %r13d
    ror          $(2), %r13d
    mov          %eax, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %edx, %r14d
    xor          %ebx, %edx
    and          %edx, %r14d
    xor          %ebx, %edx
    xor          %edx, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    addl         (4)(%rsp), %r11d
    mov          %r8d, %r13d
    ror          $(6), %r13d
    mov          %r8d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r10d, %r14d
    and          %r8d, %r14d
    xor          %r10d, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    add          %r11d, %edx
    mov          %r12d, %r13d
    ror          $(2), %r13d
    mov          %r12d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %ebx, %r14d
    xor          %eax, %ebx
    and          %ebx, %r14d
    xor          %eax, %ebx
    xor          %ebx, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    addl         (8)(%rsp), %r10d
    mov          %edx, %r13d
    ror          $(6), %r13d
    mov          %edx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r9d, %r14d
    and          %edx, %r14d
    xor          %r9d, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    add          %r10d, %ebx
    mov          %r11d, %r13d
    ror          $(2), %r13d
    mov          %r11d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %eax, %r14d
    xor          %r12d, %eax
    and          %eax, %r14d
    xor          %r12d, %eax
    xor          %eax, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    addl         (12)(%rsp), %r9d
    mov          %ebx, %r13d
    ror          $(6), %r13d
    mov          %ebx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r8d, %r14d
    and          %ebx, %r14d
    xor          %r8d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    add          %r9d, %eax
    mov          %r10d, %r13d
    ror          $(2), %r13d
    mov          %r10d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r12d, %r14d
    xor          %r11d, %r12d
    and          %r12d, %r14d
    xor          %r11d, %r12d
    xor          %r12d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    pshufd       $(250), %xmm0, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm1, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm1, %xmm7
    pshufd       $(165), %xmm3, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm2, %xmm5
    palignr      $(12), %xmm1, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm0, %xmm6
    palignr      $(12), %xmm3, %xmm6
    pshufd       $(250), %xmm1, %xmm1
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm1
    paddd        %xmm5, %xmm1
    paddd        %xmm6, %xmm1
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm1, %xmm1
    palignr      $(8), %xmm7, %xmm1
    movdqa       %xmm1, %xmm7
    paddd        (144)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r8d
    mov          %eax, %r13d
    ror          $(6), %r13d
    mov          %eax, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %edx, %r14d
    and          %eax, %r14d
    xor          %edx, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    add          %r8d, %r12d
    mov          %r9d, %r13d
    ror          $(2), %r13d
    mov          %r9d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r11d, %r14d
    xor          %r10d, %r11d
    and          %r11d, %r14d
    xor          %r10d, %r11d
    xor          %r11d, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    addl         (4)(%rsp), %edx
    mov          %r12d, %r13d
    ror          $(6), %r13d
    mov          %r12d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %ebx, %r14d
    and          %r12d, %r14d
    xor          %ebx, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    add          %edx, %r11d
    mov          %r8d, %r13d
    ror          $(2), %r13d
    mov          %r8d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r10d, %r14d
    xor          %r9d, %r10d
    and          %r10d, %r14d
    xor          %r9d, %r10d
    xor          %r10d, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    addl         (8)(%rsp), %ebx
    mov          %r11d, %r13d
    ror          $(6), %r13d
    mov          %r11d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %eax, %r14d
    and          %r11d, %r14d
    xor          %eax, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    add          %ebx, %r10d
    mov          %edx, %r13d
    ror          $(2), %r13d
    mov          %edx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r9d, %r14d
    xor          %r8d, %r9d
    and          %r9d, %r14d
    xor          %r8d, %r9d
    xor          %r9d, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    addl         (12)(%rsp), %eax
    mov          %r10d, %r13d
    ror          $(6), %r13d
    mov          %r10d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %r12d, %r14d
    and          %r10d, %r14d
    xor          %r12d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    add          %eax, %r9d
    mov          %ebx, %r13d
    ror          $(2), %r13d
    mov          %ebx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %r8d, %r14d
    xor          %edx, %r8d
    and          %r8d, %r14d
    xor          %edx, %r8d
    xor          %r8d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    pshufd       $(250), %xmm1, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm2, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm2, %xmm7
    pshufd       $(165), %xmm0, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm3, %xmm5
    palignr      $(12), %xmm2, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm1, %xmm6
    palignr      $(12), %xmm0, %xmm6
    pshufd       $(250), %xmm2, %xmm2
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm2
    paddd        %xmm5, %xmm2
    paddd        %xmm6, %xmm2
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm2, %xmm2
    palignr      $(8), %xmm7, %xmm2
    movdqa       %xmm2, %xmm7
    paddd        (160)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r12d
    mov          %r9d, %r13d
    ror          $(6), %r13d
    mov          %r9d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r11d, %r14d
    and          %r9d, %r14d
    xor          %r11d, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    add          %r12d, %r8d
    mov          %eax, %r13d
    ror          $(2), %r13d
    mov          %eax, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %edx, %r14d
    xor          %ebx, %edx
    and          %edx, %r14d
    xor          %ebx, %edx
    xor          %edx, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    addl         (4)(%rsp), %r11d
    mov          %r8d, %r13d
    ror          $(6), %r13d
    mov          %r8d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r10d, %r14d
    and          %r8d, %r14d
    xor          %r10d, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    add          %r11d, %edx
    mov          %r12d, %r13d
    ror          $(2), %r13d
    mov          %r12d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %ebx, %r14d
    xor          %eax, %ebx
    and          %ebx, %r14d
    xor          %eax, %ebx
    xor          %ebx, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    addl         (8)(%rsp), %r10d
    mov          %edx, %r13d
    ror          $(6), %r13d
    mov          %edx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r9d, %r14d
    and          %edx, %r14d
    xor          %r9d, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    add          %r10d, %ebx
    mov          %r11d, %r13d
    ror          $(2), %r13d
    mov          %r11d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %eax, %r14d
    xor          %r12d, %eax
    and          %eax, %r14d
    xor          %r12d, %eax
    xor          %eax, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    addl         (12)(%rsp), %r9d
    mov          %ebx, %r13d
    ror          $(6), %r13d
    mov          %ebx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r8d, %r14d
    and          %ebx, %r14d
    xor          %r8d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    add          %r9d, %eax
    mov          %r10d, %r13d
    ror          $(2), %r13d
    mov          %r10d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r12d, %r14d
    xor          %r11d, %r12d
    and          %r12d, %r14d
    xor          %r11d, %r12d
    xor          %r12d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    pshufd       $(250), %xmm2, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm3, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm3, %xmm7
    pshufd       $(165), %xmm1, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm0, %xmm5
    palignr      $(12), %xmm3, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm2, %xmm6
    palignr      $(12), %xmm1, %xmm6
    pshufd       $(250), %xmm3, %xmm3
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm3
    paddd        %xmm5, %xmm3
    paddd        %xmm6, %xmm3
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm3, %xmm3
    palignr      $(8), %xmm7, %xmm3
    movdqa       %xmm3, %xmm7
    paddd        (176)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r8d
    mov          %eax, %r13d
    ror          $(6), %r13d
    mov          %eax, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %edx, %r14d
    and          %eax, %r14d
    xor          %edx, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    add          %r8d, %r12d
    mov          %r9d, %r13d
    ror          $(2), %r13d
    mov          %r9d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r11d, %r14d
    xor          %r10d, %r11d
    and          %r11d, %r14d
    xor          %r10d, %r11d
    xor          %r11d, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    addl         (4)(%rsp), %edx
    mov          %r12d, %r13d
    ror          $(6), %r13d
    mov          %r12d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %ebx, %r14d
    and          %r12d, %r14d
    xor          %ebx, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    add          %edx, %r11d
    mov          %r8d, %r13d
    ror          $(2), %r13d
    mov          %r8d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r10d, %r14d
    xor          %r9d, %r10d
    and          %r10d, %r14d
    xor          %r9d, %r10d
    xor          %r10d, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    addl         (8)(%rsp), %ebx
    mov          %r11d, %r13d
    ror          $(6), %r13d
    mov          %r11d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %eax, %r14d
    and          %r11d, %r14d
    xor          %eax, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    add          %ebx, %r10d
    mov          %edx, %r13d
    ror          $(2), %r13d
    mov          %edx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r9d, %r14d
    xor          %r8d, %r9d
    and          %r9d, %r14d
    xor          %r8d, %r9d
    xor          %r9d, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    addl         (12)(%rsp), %eax
    mov          %r10d, %r13d
    ror          $(6), %r13d
    mov          %r10d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %r12d, %r14d
    and          %r10d, %r14d
    xor          %r12d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    add          %eax, %r9d
    mov          %ebx, %r13d
    ror          $(2), %r13d
    mov          %ebx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %r8d, %r14d
    xor          %edx, %r8d
    and          %r8d, %r14d
    xor          %edx, %r8d
    xor          %r8d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    pshufd       $(250), %xmm3, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm0, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm0, %xmm7
    pshufd       $(165), %xmm2, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm1, %xmm5
    palignr      $(12), %xmm0, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm3, %xmm6
    palignr      $(12), %xmm2, %xmm6
    pshufd       $(250), %xmm0, %xmm0
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm0
    paddd        %xmm5, %xmm0
    paddd        %xmm6, %xmm0
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm0, %xmm0
    palignr      $(8), %xmm7, %xmm0
    movdqa       %xmm0, %xmm7
    paddd        (192)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r12d
    mov          %r9d, %r13d
    ror          $(6), %r13d
    mov          %r9d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r11d, %r14d
    and          %r9d, %r14d
    xor          %r11d, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    add          %r12d, %r8d
    mov          %eax, %r13d
    ror          $(2), %r13d
    mov          %eax, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %edx, %r14d
    xor          %ebx, %edx
    and          %edx, %r14d
    xor          %ebx, %edx
    xor          %edx, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    addl         (4)(%rsp), %r11d
    mov          %r8d, %r13d
    ror          $(6), %r13d
    mov          %r8d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r10d, %r14d
    and          %r8d, %r14d
    xor          %r10d, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    add          %r11d, %edx
    mov          %r12d, %r13d
    ror          $(2), %r13d
    mov          %r12d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %ebx, %r14d
    xor          %eax, %ebx
    and          %ebx, %r14d
    xor          %eax, %ebx
    xor          %ebx, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    addl         (8)(%rsp), %r10d
    mov          %edx, %r13d
    ror          $(6), %r13d
    mov          %edx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r9d, %r14d
    and          %edx, %r14d
    xor          %r9d, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    add          %r10d, %ebx
    mov          %r11d, %r13d
    ror          $(2), %r13d
    mov          %r11d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %eax, %r14d
    xor          %r12d, %eax
    and          %eax, %r14d
    xor          %r12d, %eax
    xor          %eax, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    addl         (12)(%rsp), %r9d
    mov          %ebx, %r13d
    ror          $(6), %r13d
    mov          %ebx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r8d, %r14d
    and          %ebx, %r14d
    xor          %r8d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    add          %r9d, %eax
    mov          %r10d, %r13d
    ror          $(2), %r13d
    mov          %r10d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r12d, %r14d
    xor          %r11d, %r12d
    and          %r12d, %r14d
    xor          %r11d, %r12d
    xor          %r12d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    pshufd       $(250), %xmm0, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm1, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm1, %xmm7
    pshufd       $(165), %xmm3, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm2, %xmm5
    palignr      $(12), %xmm1, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm0, %xmm6
    palignr      $(12), %xmm3, %xmm6
    pshufd       $(250), %xmm1, %xmm1
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm1
    paddd        %xmm5, %xmm1
    paddd        %xmm6, %xmm1
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm1, %xmm1
    palignr      $(8), %xmm7, %xmm1
    movdqa       %xmm1, %xmm7
    paddd        (208)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r8d
    mov          %eax, %r13d
    ror          $(6), %r13d
    mov          %eax, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %edx, %r14d
    and          %eax, %r14d
    xor          %edx, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    add          %r8d, %r12d
    mov          %r9d, %r13d
    ror          $(2), %r13d
    mov          %r9d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r11d, %r14d
    xor          %r10d, %r11d
    and          %r11d, %r14d
    xor          %r10d, %r11d
    xor          %r11d, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    addl         (4)(%rsp), %edx
    mov          %r12d, %r13d
    ror          $(6), %r13d
    mov          %r12d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %ebx, %r14d
    and          %r12d, %r14d
    xor          %ebx, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    add          %edx, %r11d
    mov          %r8d, %r13d
    ror          $(2), %r13d
    mov          %r8d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r10d, %r14d
    xor          %r9d, %r10d
    and          %r10d, %r14d
    xor          %r9d, %r10d
    xor          %r10d, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    addl         (8)(%rsp), %ebx
    mov          %r11d, %r13d
    ror          $(6), %r13d
    mov          %r11d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %eax, %r14d
    and          %r11d, %r14d
    xor          %eax, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    add          %ebx, %r10d
    mov          %edx, %r13d
    ror          $(2), %r13d
    mov          %edx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r9d, %r14d
    xor          %r8d, %r9d
    and          %r9d, %r14d
    xor          %r8d, %r9d
    xor          %r9d, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    addl         (12)(%rsp), %eax
    mov          %r10d, %r13d
    ror          $(6), %r13d
    mov          %r10d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %r12d, %r14d
    and          %r10d, %r14d
    xor          %r12d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    add          %eax, %r9d
    mov          %ebx, %r13d
    ror          $(2), %r13d
    mov          %ebx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %r8d, %r14d
    xor          %edx, %r8d
    and          %r8d, %r14d
    xor          %edx, %r8d
    xor          %r8d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    pshufd       $(250), %xmm1, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm2, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm2, %xmm7
    pshufd       $(165), %xmm0, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm3, %xmm5
    palignr      $(12), %xmm2, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm1, %xmm6
    palignr      $(12), %xmm0, %xmm6
    pshufd       $(250), %xmm2, %xmm2
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm2
    paddd        %xmm5, %xmm2
    paddd        %xmm6, %xmm2
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm2, %xmm2
    palignr      $(8), %xmm7, %xmm2
    movdqa       %xmm2, %xmm7
    paddd        (224)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r12d
    mov          %r9d, %r13d
    ror          $(6), %r13d
    mov          %r9d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r11d, %r14d
    and          %r9d, %r14d
    xor          %r11d, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    add          %r12d, %r8d
    mov          %eax, %r13d
    ror          $(2), %r13d
    mov          %eax, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %edx, %r14d
    xor          %ebx, %edx
    and          %edx, %r14d
    xor          %ebx, %edx
    xor          %edx, %r14d
    add          %r13d, %r12d
    add          %r14d, %r12d
    addl         (4)(%rsp), %r11d
    mov          %r8d, %r13d
    ror          $(6), %r13d
    mov          %r8d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r10d, %r14d
    and          %r8d, %r14d
    xor          %r10d, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    add          %r11d, %edx
    mov          %r12d, %r13d
    ror          $(2), %r13d
    mov          %r12d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %ebx, %r14d
    xor          %eax, %ebx
    and          %ebx, %r14d
    xor          %eax, %ebx
    xor          %ebx, %r14d
    add          %r13d, %r11d
    add          %r14d, %r11d
    addl         (8)(%rsp), %r10d
    mov          %edx, %r13d
    ror          $(6), %r13d
    mov          %edx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r9d, %r14d
    and          %edx, %r14d
    xor          %r9d, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    add          %r10d, %ebx
    mov          %r11d, %r13d
    ror          $(2), %r13d
    mov          %r11d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %eax, %r14d
    xor          %r12d, %eax
    and          %eax, %r14d
    xor          %r12d, %eax
    xor          %eax, %r14d
    add          %r13d, %r10d
    add          %r14d, %r10d
    addl         (12)(%rsp), %r9d
    mov          %ebx, %r13d
    ror          $(6), %r13d
    mov          %ebx, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r8d, %r14d
    and          %ebx, %r14d
    xor          %r8d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    add          %r9d, %eax
    mov          %r10d, %r13d
    ror          $(2), %r13d
    mov          %r10d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r10d, %r14d
    xor          %r12d, %r14d
    xor          %r11d, %r12d
    and          %r12d, %r14d
    xor          %r11d, %r12d
    xor          %r12d, %r14d
    add          %r13d, %r9d
    add          %r14d, %r9d
    pshufd       $(250), %xmm2, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm3, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm3, %xmm7
    pshufd       $(165), %xmm1, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm0, %xmm5
    palignr      $(12), %xmm3, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm2, %xmm6
    palignr      $(12), %xmm1, %xmm6
    pshufd       $(250), %xmm3, %xmm3
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm3
    paddd        %xmm5, %xmm3
    paddd        %xmm6, %xmm3
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm3, %xmm3
    palignr      $(8), %xmm7, %xmm3
    movdqa       %xmm3, %xmm7
    paddd        (240)(%rcx), %xmm7
    movdqa       %xmm7, (%rsp)
    addl         (%rsp), %r8d
    mov          %eax, %r13d
    ror          $(6), %r13d
    mov          %eax, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %edx, %r14d
    and          %eax, %r14d
    xor          %edx, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    add          %r8d, %r12d
    mov          %r9d, %r13d
    ror          $(2), %r13d
    mov          %r9d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r9d, %r14d
    xor          %r11d, %r14d
    xor          %r10d, %r11d
    and          %r11d, %r14d
    xor          %r10d, %r11d
    xor          %r11d, %r14d
    add          %r13d, %r8d
    add          %r14d, %r8d
    addl         (4)(%rsp), %edx
    mov          %r12d, %r13d
    ror          $(6), %r13d
    mov          %r12d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %eax, %r14d
    xor          %ebx, %r14d
    and          %r12d, %r14d
    xor          %ebx, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    add          %edx, %r11d
    mov          %r8d, %r13d
    ror          $(2), %r13d
    mov          %r8d, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %r8d, %r14d
    xor          %r10d, %r14d
    xor          %r9d, %r10d
    and          %r10d, %r14d
    xor          %r9d, %r10d
    xor          %r10d, %r14d
    add          %r13d, %edx
    add          %r14d, %edx
    addl         (8)(%rsp), %ebx
    mov          %r11d, %r13d
    ror          $(6), %r13d
    mov          %r11d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r12d, %r14d
    xor          %eax, %r14d
    and          %r11d, %r14d
    xor          %eax, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    add          %ebx, %r10d
    mov          %edx, %r13d
    ror          $(2), %r13d
    mov          %edx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %edx, %r14d
    xor          %r9d, %r14d
    xor          %r8d, %r9d
    and          %r9d, %r14d
    xor          %r8d, %r9d
    xor          %r9d, %r14d
    add          %r13d, %ebx
    add          %r14d, %ebx
    addl         (12)(%rsp), %eax
    mov          %r10d, %r13d
    ror          $(6), %r13d
    mov          %r10d, %r14d
    ror          $(11), %r14d
    xor          %r14d, %r13d
    ror          $(14), %r14d
    xor          %r14d, %r13d
    mov          %r11d, %r14d
    xor          %r12d, %r14d
    and          %r10d, %r14d
    xor          %r12d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    add          %eax, %r9d
    mov          %ebx, %r13d
    ror          $(2), %r13d
    mov          %ebx, %r14d
    ror          $(13), %r14d
    xor          %r14d, %r13d
    ror          $(9), %r14d
    xor          %r14d, %r13d
    mov          %ebx, %r14d
    xor          %r8d, %r14d
    xor          %edx, %r8d
    and          %r8d, %r14d
    xor          %edx, %r8d
    xor          %r8d, %r14d
    add          %r13d, %eax
    add          %r14d, %eax
    addl         %eax, (%rdi)
    addl         %ebx, (4)(%rdi)
    addl         %edx, (8)(%rdi)
    addl         %r8d, (12)(%rdi)
    addl         %r9d, (16)(%rdi)
    addl         %r10d, (20)(%rdi)
    addl         %r11d, (24)(%rdi)
    addl         %r12d, (28)(%rdi)
    add          $(64), %rsi
    subq         $(64), (16)(%rsp)
    jg           .Lsha256_block_loopgas_1
    add          $(40), %rsp
 
    pop          %r15
 
    pop          %r14
 
    pop          %r13
 
    pop          %r12
 
    pop          %rbp
 
    pop          %rbx
 
    ret
 
