###############################################################################
# Copyright 2019 Intel Corporation
# All Rights Reserved.
#
# If this  software was obtained  under the  Intel Simplified  Software License,
# the following terms apply:
#
# The source code,  information  and material  ("Material") contained  herein is
# owned by Intel Corporation or its  suppliers or licensors,  and  title to such
# Material remains with Intel  Corporation or its  suppliers or  licensors.  The
# Material  contains  proprietary  information  of  Intel or  its suppliers  and
# licensors.  The Material is protected by  worldwide copyright  laws and treaty
# provisions.  No part  of  the  Material   may  be  used,  copied,  reproduced,
# modified, published,  uploaded, posted, transmitted,  distributed or disclosed
# in any way without Intel's prior express written permission.  No license under
# any patent,  copyright or other  intellectual property rights  in the Material
# is granted to  or  conferred  upon  you,  either   expressly,  by implication,
# inducement,  estoppel  or  otherwise.  Any  license   under such  intellectual
# property rights must be express and approved by Intel in writing.
#
# Unless otherwise agreed by Intel in writing,  you may not remove or alter this
# notice or  any  other  notice   embedded  in  Materials  by  Intel  or Intel's
# suppliers or licensors in any way.
#
#
# If this  software  was obtained  under the  Apache License,  Version  2.0 (the
# "License"), the following terms apply:
#
# You may  not use this  file except  in compliance  with  the License.  You may
# obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
#
# Unless  required  by   applicable  law  or  agreed  to  in  writing,  software
# distributed under the License  is distributed  on an  "AS IS"  BASIS,  WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the   License  for the   specific  language   governing   permissions  and
# limitations under the License.
###############################################################################

 
.text
.p2align 4, 0x90
SWP_BYTE: 
 
pByteSwp:
.byte  3,2,1,0, 7,6,5,4, 11,10,9,8, 15,14,13,12 
.p2align 4, 0x90
 
.globl _UpdateSHA256

 
_UpdateSHA256:
    push         %ebp
    mov          %esp, %ebp
    push         %ebx
    push         %esi
    push         %edi
 
    sub          $(52), %esp
.Lsha256_block_loopgas_1: 
    movl         (8)(%ebp), %eax
    movdqu       (%eax), %xmm0
    movdqu       (16)(%eax), %xmm1
    movdqu       %xmm0, (%esp)
    movdqu       %xmm1, (16)(%esp)
    call         .L__0000gas_1
.L__0000gas_1:
    pop          %eax
    sub          $(.L__0000gas_1-SWP_BYTE), %eax
    movdqa       ((pByteSwp-SWP_BYTE))(%eax), %xmm6
    movl         (12)(%ebp), %eax
    movl         (20)(%ebp), %ebx
    movdqu       (%eax), %xmm0
    movdqu       (16)(%eax), %xmm1
    movdqu       (32)(%eax), %xmm2
    movdqu       (48)(%eax), %xmm3
 
    mov          (16)(%esp), %eax
    mov          (%esp), %edx
    pshufb       %xmm6, %xmm0
    movdqa       %xmm0, %xmm7
    paddd        (%ebx), %xmm7
    movdqu       %xmm7, (32)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (20)(%esp), %edi
    xor          (24)(%esp), %edi
    and          %eax, %edi
    xor          (24)(%esp), %edi
    mov          (28)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (32)(%esp), %eax
    movl         (4)(%esp), %esi
    movl         (8)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (12)(%esp), %eax
    mov          %edx, (28)(%esp)
    mov          %eax, (12)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (16)(%esp), %edi
    xor          (20)(%esp), %edi
    and          %eax, %edi
    xor          (20)(%esp), %edi
    mov          (24)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (36)(%esp), %eax
    movl         (%esp), %esi
    movl         (4)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (8)(%esp), %eax
    mov          %edx, (24)(%esp)
    mov          %eax, (8)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (12)(%esp), %edi
    xor          (16)(%esp), %edi
    and          %eax, %edi
    xor          (16)(%esp), %edi
    mov          (20)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (40)(%esp), %eax
    movl         (28)(%esp), %esi
    movl         (%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (4)(%esp), %eax
    mov          %edx, (20)(%esp)
    mov          %eax, (4)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (8)(%esp), %edi
    xor          (12)(%esp), %edi
    and          %eax, %edi
    xor          (12)(%esp), %edi
    mov          (16)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (44)(%esp), %eax
    movl         (24)(%esp), %esi
    movl         (28)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (%esp), %eax
    mov          %edx, (16)(%esp)
    mov          %eax, (%esp)
    pshufb       %xmm6, %xmm1
    movdqa       %xmm1, %xmm7
    paddd        (16)(%ebx), %xmm7
    movdqu       %xmm7, (32)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (4)(%esp), %edi
    xor          (8)(%esp), %edi
    and          %eax, %edi
    xor          (8)(%esp), %edi
    mov          (12)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (32)(%esp), %eax
    movl         (20)(%esp), %esi
    movl         (24)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (28)(%esp), %eax
    mov          %edx, (12)(%esp)
    mov          %eax, (28)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (%esp), %edi
    xor          (4)(%esp), %edi
    and          %eax, %edi
    xor          (4)(%esp), %edi
    mov          (8)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (36)(%esp), %eax
    movl         (16)(%esp), %esi
    movl         (20)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (24)(%esp), %eax
    mov          %edx, (8)(%esp)
    mov          %eax, (24)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (28)(%esp), %edi
    xor          (%esp), %edi
    and          %eax, %edi
    xor          (%esp), %edi
    mov          (4)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (40)(%esp), %eax
    movl         (12)(%esp), %esi
    movl         (16)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (20)(%esp), %eax
    mov          %edx, (4)(%esp)
    mov          %eax, (20)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (24)(%esp), %edi
    xor          (28)(%esp), %edi
    and          %eax, %edi
    xor          (28)(%esp), %edi
    mov          (%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (44)(%esp), %eax
    movl         (8)(%esp), %esi
    movl         (12)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (16)(%esp), %eax
    mov          %edx, (%esp)
    mov          %eax, (16)(%esp)
    pshufb       %xmm6, %xmm2
    movdqa       %xmm2, %xmm7
    paddd        (32)(%ebx), %xmm7
    movdqu       %xmm7, (32)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (20)(%esp), %edi
    xor          (24)(%esp), %edi
    and          %eax, %edi
    xor          (24)(%esp), %edi
    mov          (28)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (32)(%esp), %eax
    movl         (4)(%esp), %esi
    movl         (8)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (12)(%esp), %eax
    mov          %edx, (28)(%esp)
    mov          %eax, (12)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (16)(%esp), %edi
    xor          (20)(%esp), %edi
    and          %eax, %edi
    xor          (20)(%esp), %edi
    mov          (24)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (36)(%esp), %eax
    movl         (%esp), %esi
    movl         (4)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (8)(%esp), %eax
    mov          %edx, (24)(%esp)
    mov          %eax, (8)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (12)(%esp), %edi
    xor          (16)(%esp), %edi
    and          %eax, %edi
    xor          (16)(%esp), %edi
    mov          (20)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (40)(%esp), %eax
    movl         (28)(%esp), %esi
    movl         (%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (4)(%esp), %eax
    mov          %edx, (20)(%esp)
    mov          %eax, (4)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (8)(%esp), %edi
    xor          (12)(%esp), %edi
    and          %eax, %edi
    xor          (12)(%esp), %edi
    mov          (16)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (44)(%esp), %eax
    movl         (24)(%esp), %esi
    movl         (28)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (%esp), %eax
    mov          %edx, (16)(%esp)
    mov          %eax, (%esp)
    pshufb       %xmm6, %xmm3
    movdqa       %xmm3, %xmm7
    paddd        (48)(%ebx), %xmm7
    movdqu       %xmm7, (32)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (4)(%esp), %edi
    xor          (8)(%esp), %edi
    and          %eax, %edi
    xor          (8)(%esp), %edi
    mov          (12)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (32)(%esp), %eax
    movl         (20)(%esp), %esi
    movl         (24)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (28)(%esp), %eax
    mov          %edx, (12)(%esp)
    mov          %eax, (28)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (%esp), %edi
    xor          (4)(%esp), %edi
    and          %eax, %edi
    xor          (4)(%esp), %edi
    mov          (8)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (36)(%esp), %eax
    movl         (16)(%esp), %esi
    movl         (20)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (24)(%esp), %eax
    mov          %edx, (8)(%esp)
    mov          %eax, (24)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (28)(%esp), %edi
    xor          (%esp), %edi
    and          %eax, %edi
    xor          (%esp), %edi
    mov          (4)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (40)(%esp), %eax
    movl         (12)(%esp), %esi
    movl         (16)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (20)(%esp), %eax
    mov          %edx, (4)(%esp)
    mov          %eax, (20)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (24)(%esp), %edi
    xor          (28)(%esp), %edi
    and          %eax, %edi
    xor          (28)(%esp), %edi
    mov          (%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (44)(%esp), %eax
    movl         (8)(%esp), %esi
    movl         (12)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (16)(%esp), %eax
    mov          %edx, (%esp)
    mov          %eax, (16)(%esp)
    movl         $(48), (48)(%esp)
.Lloop_16_63gas_1: 
    add          $(64), %ebx
    pshufd       $(250), %xmm3, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm0, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm0, %xmm7
    pshufd       $(165), %xmm2, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm1, %xmm5
    palignr      $(12), %xmm0, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm3, %xmm6
    palignr      $(12), %xmm2, %xmm6
    pshufd       $(250), %xmm0, %xmm0
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm0
    paddd        %xmm5, %xmm0
    paddd        %xmm6, %xmm0
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm0, %xmm0
    palignr      $(8), %xmm7, %xmm0
    movdqa       %xmm0, %xmm7
    paddd        (%ebx), %xmm7
    movdqu       %xmm7, (32)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (20)(%esp), %edi
    xor          (24)(%esp), %edi
    and          %eax, %edi
    xor          (24)(%esp), %edi
    mov          (28)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (32)(%esp), %eax
    movl         (4)(%esp), %esi
    movl         (8)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (12)(%esp), %eax
    mov          %edx, (28)(%esp)
    mov          %eax, (12)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (16)(%esp), %edi
    xor          (20)(%esp), %edi
    and          %eax, %edi
    xor          (20)(%esp), %edi
    mov          (24)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (36)(%esp), %eax
    movl         (%esp), %esi
    movl         (4)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (8)(%esp), %eax
    mov          %edx, (24)(%esp)
    mov          %eax, (8)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (12)(%esp), %edi
    xor          (16)(%esp), %edi
    and          %eax, %edi
    xor          (16)(%esp), %edi
    mov          (20)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (40)(%esp), %eax
    movl         (28)(%esp), %esi
    movl         (%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (4)(%esp), %eax
    mov          %edx, (20)(%esp)
    mov          %eax, (4)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (8)(%esp), %edi
    xor          (12)(%esp), %edi
    and          %eax, %edi
    xor          (12)(%esp), %edi
    mov          (16)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (44)(%esp), %eax
    movl         (24)(%esp), %esi
    movl         (28)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (%esp), %eax
    mov          %edx, (16)(%esp)
    mov          %eax, (%esp)
    pshufd       $(250), %xmm0, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm1, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm1, %xmm7
    pshufd       $(165), %xmm3, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm2, %xmm5
    palignr      $(12), %xmm1, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm0, %xmm6
    palignr      $(12), %xmm3, %xmm6
    pshufd       $(250), %xmm1, %xmm1
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm1
    paddd        %xmm5, %xmm1
    paddd        %xmm6, %xmm1
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm1, %xmm1
    palignr      $(8), %xmm7, %xmm1
    movdqa       %xmm1, %xmm7
    paddd        (16)(%ebx), %xmm7
    movdqu       %xmm7, (32)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (4)(%esp), %edi
    xor          (8)(%esp), %edi
    and          %eax, %edi
    xor          (8)(%esp), %edi
    mov          (12)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (32)(%esp), %eax
    movl         (20)(%esp), %esi
    movl         (24)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (28)(%esp), %eax
    mov          %edx, (12)(%esp)
    mov          %eax, (28)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (%esp), %edi
    xor          (4)(%esp), %edi
    and          %eax, %edi
    xor          (4)(%esp), %edi
    mov          (8)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (36)(%esp), %eax
    movl         (16)(%esp), %esi
    movl         (20)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (24)(%esp), %eax
    mov          %edx, (8)(%esp)
    mov          %eax, (24)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (28)(%esp), %edi
    xor          (%esp), %edi
    and          %eax, %edi
    xor          (%esp), %edi
    mov          (4)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (40)(%esp), %eax
    movl         (12)(%esp), %esi
    movl         (16)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (20)(%esp), %eax
    mov          %edx, (4)(%esp)
    mov          %eax, (20)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (24)(%esp), %edi
    xor          (28)(%esp), %edi
    and          %eax, %edi
    xor          (28)(%esp), %edi
    mov          (%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (44)(%esp), %eax
    movl         (8)(%esp), %esi
    movl         (12)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (16)(%esp), %eax
    mov          %edx, (%esp)
    mov          %eax, (16)(%esp)
    pshufd       $(250), %xmm1, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm2, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm2, %xmm7
    pshufd       $(165), %xmm0, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm3, %xmm5
    palignr      $(12), %xmm2, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm1, %xmm6
    palignr      $(12), %xmm0, %xmm6
    pshufd       $(250), %xmm2, %xmm2
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm2
    paddd        %xmm5, %xmm2
    paddd        %xmm6, %xmm2
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm2, %xmm2
    palignr      $(8), %xmm7, %xmm2
    movdqa       %xmm2, %xmm7
    paddd        (32)(%ebx), %xmm7
    movdqu       %xmm7, (32)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (20)(%esp), %edi
    xor          (24)(%esp), %edi
    and          %eax, %edi
    xor          (24)(%esp), %edi
    mov          (28)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (32)(%esp), %eax
    movl         (4)(%esp), %esi
    movl         (8)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (12)(%esp), %eax
    mov          %edx, (28)(%esp)
    mov          %eax, (12)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (16)(%esp), %edi
    xor          (20)(%esp), %edi
    and          %eax, %edi
    xor          (20)(%esp), %edi
    mov          (24)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (36)(%esp), %eax
    movl         (%esp), %esi
    movl         (4)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (8)(%esp), %eax
    mov          %edx, (24)(%esp)
    mov          %eax, (8)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (12)(%esp), %edi
    xor          (16)(%esp), %edi
    and          %eax, %edi
    xor          (16)(%esp), %edi
    mov          (20)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (40)(%esp), %eax
    movl         (28)(%esp), %esi
    movl         (%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (4)(%esp), %eax
    mov          %edx, (20)(%esp)
    mov          %eax, (4)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (8)(%esp), %edi
    xor          (12)(%esp), %edi
    and          %eax, %edi
    xor          (12)(%esp), %edi
    mov          (16)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (44)(%esp), %eax
    movl         (24)(%esp), %esi
    movl         (28)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (%esp), %eax
    mov          %edx, (16)(%esp)
    mov          %eax, (%esp)
    pshufd       $(250), %xmm2, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    pshufd       $(165), %xmm3, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    pshufd       $(80), %xmm3, %xmm7
    pshufd       $(165), %xmm1, %xmm6
    paddd        %xmm4, %xmm7
    paddd        %xmm5, %xmm7
    paddd        %xmm6, %xmm7
    pshufd       $(160), %xmm7, %xmm4
    movdqa       %xmm4, %xmm6
    psrld        $(10), %xmm4
    psrlq        $(17), %xmm6
    pxor         %xmm6, %xmm4
    psrlq        $(2), %xmm6
    pxor         %xmm6, %xmm4
    movdqa       %xmm0, %xmm5
    palignr      $(12), %xmm3, %xmm5
    pshufd       $(80), %xmm5, %xmm5
    movdqa       %xmm5, %xmm6
    psrld        $(3), %xmm5
    psrlq        $(7), %xmm6
    pxor         %xmm6, %xmm5
    psrlq        $(11), %xmm6
    pxor         %xmm6, %xmm5
    movdqa       %xmm2, %xmm6
    palignr      $(12), %xmm1, %xmm6
    pshufd       $(250), %xmm3, %xmm3
    pshufd       $(80), %xmm6, %xmm6
    paddd        %xmm4, %xmm3
    paddd        %xmm5, %xmm3
    paddd        %xmm6, %xmm3
    pshufd       $(136), %xmm7, %xmm7
    pshufd       $(136), %xmm3, %xmm3
    palignr      $(8), %xmm7, %xmm3
    movdqa       %xmm3, %xmm7
    paddd        (48)(%ebx), %xmm7
    movdqu       %xmm7, (32)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (4)(%esp), %edi
    xor          (8)(%esp), %edi
    and          %eax, %edi
    xor          (8)(%esp), %edi
    mov          (12)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (32)(%esp), %eax
    movl         (20)(%esp), %esi
    movl         (24)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (28)(%esp), %eax
    mov          %edx, (12)(%esp)
    mov          %eax, (28)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (%esp), %edi
    xor          (4)(%esp), %edi
    and          %eax, %edi
    xor          (4)(%esp), %edi
    mov          (8)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (36)(%esp), %eax
    movl         (16)(%esp), %esi
    movl         (20)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (24)(%esp), %eax
    mov          %edx, (8)(%esp)
    mov          %eax, (24)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (28)(%esp), %edi
    xor          (%esp), %edi
    and          %eax, %edi
    xor          (%esp), %edi
    mov          (4)(%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (40)(%esp), %eax
    movl         (12)(%esp), %esi
    movl         (16)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (20)(%esp), %eax
    mov          %edx, (4)(%esp)
    mov          %eax, (20)(%esp)
    mov          %eax, %esi
    ror          $(6), %esi
    mov          %eax, %ecx
    ror          $(11), %ecx
    xor          %ecx, %esi
    ror          $(14), %ecx
    xor          %ecx, %esi
    mov          (24)(%esp), %edi
    xor          (28)(%esp), %edi
    and          %eax, %edi
    xor          (28)(%esp), %edi
    mov          (%esp), %eax
    add          %esi, %eax
    add          %edi, %eax
    addl         (44)(%esp), %eax
    movl         (8)(%esp), %esi
    movl         (12)(%esp), %ecx
    mov          %edx, %edi
    xor          %ecx, %edi
    xor          %esi, %ecx
    and          %ecx, %edi
    xor          %esi, %ecx
    xor          %ecx, %edi
    mov          %edx, %esi
    ror          $(2), %esi
    mov          %edx, %ecx
    ror          $(13), %ecx
    xor          %ecx, %esi
    ror          $(9), %ecx
    xor          %ecx, %esi
    lea          (%edi,%esi), %edx
    add          %eax, %edx
    add          (16)(%esp), %eax
    mov          %edx, (%esp)
    mov          %eax, (16)(%esp)
    subl         $(16), (48)(%esp)
    jg           .Lloop_16_63gas_1
    movl         (8)(%ebp), %eax
    movdqu       (%esp), %xmm0
    movdqu       (16)(%esp), %xmm1
    movdqu       (%eax), %xmm7
    paddd        %xmm0, %xmm7
    movdqu       %xmm7, (%eax)
    movdqu       (16)(%eax), %xmm7
    paddd        %xmm1, %xmm7
    movdqu       %xmm7, (16)(%eax)
    addl         $(64), (12)(%ebp)
    subl         $(64), (16)(%ebp)
    jg           .Lsha256_block_loopgas_1
    add          $(52), %esp
    pop          %edi
    pop          %esi
    pop          %ebx
    pop          %ebp
    ret
 
